version: '1'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "81:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - my-network  
    environment:
          - BACKEND_API_URL=http://backend:3000/api/users      
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/usr/share/app/src
      - ./backend/nodemon.json:/usr/share/app/nodemon.json
    networks:
      - my-network       
    depends_on:
      - db
  db:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - my-network       
    # volumes:
    #   - D:\learn\docker\html_express_mysql\data\mysql:/var/lib/mysql
networks:
  my-network:
    driver: bridge  
