version: '1'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "81:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - my-network   
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/usr/share/app/src
      - ./backend/nodemon.json:/usr/share/app/nodemon.json
    env_file:
      - ./backend.env    
    networks:
      - my-network       
    depends_on:
      - db
  db:
    build:
      context: ./db
    env_file:
      - ./db.env    
    networks:
      - my-network       
    volumes:
      - ./database_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  my-network:
    driver: bridge